CREATE TABLE CONVERSATION_SETTINGS (
    conversation_id VARCHAR(255) NOT NULL,
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'UTC',
    PRIMARY KEY (conversation_id)
);

ALTER TABLE REMINDERS ADD COLUMN zone_id VARCHAR(64) NOT NULL DEFAULT 'UTC';
